dataset_config:
  hateful_memes:
    processors:
      text_processor:
        params:
          max_length: null
          model_file: wiki.en.bin
        type: fasttext_sentence_vector
evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
optimizer:
  params:
    eps: 1e-8
    lr: 5e-5
  type: adam_w
scheduler:
  params:
    num_training_steps: ${training.max_updates}
    num_warmup_steps: 2000
  type: warmup_linear
training:
  batch_size: 64
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false
  find_unused_parameters: true
  lr_scheduler: true
  max_updates: 22000
