model_config:
  concat_vl:
    classifier:
      params:
        in_dim: 512
        num_layers: 0
        out_dim: ${model_config.concat_vl.num_classes}
      type: mlp
    dropout: 0.1
    fusion:
      params:
        in_features: 2348
        out_features: 512
    image_encoder:
      params:
        num_output_features: 1
        pool_type: avg
        pretrained: true
      type: resnet152
    losses:
    - cross_entropy
    num_classes: 2
    text_encoder:
      params:
        in_dim: 300
        module: linear
        out_dim: 300
